#!/usr/bin/env node
// Reads tokens/*.json and writes dist/tokens.css, dist/theme.css, dist/tokens.js, dist/tokens.d.ts.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const tokensDir = path.join(root, "tokens");
const distDir = path.join(root, "dist");

function readJson(name) {
  return JSON.parse(readFileSync(path.join(tokensDir, name), "utf8"));
}

mkdirSync(distDir, { recursive: true });

const color = readJson("color.json");
const theme = readJson("theme.json");
const scale = readJson("scale.json");

function block(selector, props) {
  const lines = Object.entries(props).map(([name, value]) => `  ${name}: ${value};`);
  return `${selector} {\n${lines.join("\n")}\n}\n`;
}

const tokensCss =
  block(":root", { ...color.light, ...scale }) + "\n" + block(".dark", color.dark);
writeFileSync(path.join(distDir, "tokens.css"), tokensCss);

const themeCss = block("@theme inline", theme);
writeFileSync(path.join(distDir, "theme.css"), themeCss);

const tokensJs = `// Generated by scripts/build.mjs from tokens/*.json. Do not edit by hand.
export const light = ${JSON.stringify(color.light, null, 2)};

export const dark = ${JSON.stringify(color.dark, null, 2)};

export const theme = ${JSON.stringify(theme, null, 2)};

export const scale = ${JSON.stringify(scale, null, 2)};
`;
writeFileSync(path.join(distDir, "tokens.js"), tokensJs);

const tokensDts = `export declare const light: Record<string, string>;
export declare const dark: Record<string, string>;
export declare const theme: Record<string, string>;
export declare const scale: Record<string, string>;
`;
writeFileSync(path.join(distDir, "tokens.d.ts"), tokensDts);

console.log("wrote dist/tokens.css, dist/theme.css, dist/tokens.js, dist/tokens.d.ts");
